[project]
name = "do-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.4.1",
    "langchain>=1.2.7",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "mcp>=1.26.0",
    "ollama>=0.6.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.2",
]
